### ISSUE TITLE
Raspbian Buster full compatibility

### ISSUE THREAD

**Issue by empierre** [empierre/MyDomoAtHome#184]
https://www.raspberrypi.org/blog/buster-the-new-version-of-raspbian/

**Comment by empierre** [comment]
Debian Buster requires node.js v10.x !!
nodejs (10.15.2~dfsg-2)

**Comment by empierre** [comment]
raspbian 9 stretch supports 8 only
    nodejs | 8.11.1~dfsg-2~bpo9+1 | http://archive.raspberrypi.org/debian stretch/main armhf 
    nodejs | 4.8.2~dfsg-1 | http://raspbian.raspberrypi.org/raspbian stretch/main armhf Packages

node 8 not working, fallback:
sudo apt-cache madison nodejs
    nodejs | 8.11.1~dfsg-2~bpo9+1 | http://archive.raspberrypi.org/debian stretch/main armhf Packages
    nodejs | 4.8.2~dfsg-1 | http://raspbian.raspberrypi.org/raspbian stretch/main armhf Packages
sudo apt-get install nodejs=4.8.2~dfsg-1

**Comment by empierre** [comment]
Ubuntu 16.04.6 LTS (Xenial Xerus) 
    nodejs | 4.2.6~dfsg-1ubuntu4.2 | http://ports.ubuntu.com/ubuntu-ports xenial-updates/universe armhf 
    nodejs | 4.2.6~dfsg-1ubuntu4.2 | http://ports.ubuntu.com/ubuntu-ports xenial-security/universe armhf 
    nodejs | 4.2.6~dfsg-1ubuntu4 | http://ports.ubuntu.com/ubuntu-ports xenial/universe armhf 
    nodejs |      4.2.2 | https://www.e-nef.com/domoticz/mdah  Packages

**Comment by empierre** [comment]
fixed, just need to install npm, doc updated

**Comment by Potjoe-97** [comment]
Hi empierre, 

I'm having troubles installing nodejs and mdah on latest buster build... are you sure it is solved ? I've followed the updated readme, still not able to install the packages. 

Thanks

Edit : I have a fresh buster install.

**Comment by empierre** [comment]
Hello,

  Please see specific wiki procedure for bustier, you need two packages
where previous distros needed only one

**Comment by Potjoe-97** [comment]
Hi, 

Actually despite following the specific instructions fot buster, i was using a noobs install.. I've just made a full iso fresh install and everything went well :) Thank you again.
